- name: Installer NGINX sur AWS
  hosts: web
  become: true
  tasks:
    - name: Mise à jour apt
      apt:
        update_cache: yes

    - name: Installer nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer nginx
      service:
        name: nginx
        state: started
        enabled: yes
