- name: Installer NGINX sur AWS
  hosts: web
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer NGINX
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer NGINX
      service:
        name: nginx
        state: started
        enabled: yes
