name: Deploy Infra and Configure NGINX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform-aws init

      - name: Terraform Plan
        run: terraform -chdir=terraform-aws plan

      - name: Terraform Apply
        run: terraform -chdir=terraform-aws apply -auto-approve

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
